spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db-auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: ${CHANGE_LOG:classpath:db/changelog/db.changelog-master.xml}
    enabled: true

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  virtual-host: ${RABBITMQ_VHOST:/}
  publisher-confirm-type: correlated
  publisher-returns: true
  template:
    mandatory: true
  queue:
    user-created: ${RABBITMQ_QUEUE_USER_CREATED:user.created}
  exchange:
    user-events: ${RABBITMQ_EXCHANGE_USER_EVENTS:user.events}
  routing-key:
    user-created: ${RABBITMQ_ROUTING_KEY_USER_CREATED:user.created}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days in milliseconds

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.graduationproject: ${LOG_LEVEL:DEBUG}
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.amqp: ${LOG_LEVEL:INFO}
    com.rabbitmq: DEBUG
  file:
    name: logs/auth-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
      total-size-cap: 1GB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}
  