-- V3__add_sample_data.sql
START TRANSACTION;

-- Dữ liệu mẫu cho auth_users
INSERT INTO auth_users (user_id, password, provider, created_at, updated_at)
VALUES
(1, '$2a$10$rDkPvvAFV6GgJjXpYWJhUOQZx1Yw8YQZx1Yw8YQZx1Yw8YQZx1Yw8', 'local', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '$2a$10$rDkPvvAFV6GgJjXpYWJhUOQZx1Yw8YQZx1Yw8YQZx1Yw8YQZx1Yw8', 'local', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '$2a$10$rDkPvvAFV6GgJjXpYWJhUOQZx1Yw8YQZx1Yw8YQZx1Yw8YQZx1Yw8', 'local', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '$2a$10$rDkPvvAFV6GgJjXpYWJhUOQZx1Yw8YQZx1Yw8YQZx1Yw8YQZx1Yw8', 'local', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '$2a$10$rDkPvvAFV6GgJjXpYWJhUOQZx1Yw8YQZx1Yw8YQZx1Yw8YQZx1Yw8', 'local', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT; 
